modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/Manlet008/SeasonPlayerMinimum/issues"
displayURL="https://github.com/Manlet008/SeasonPlayerMinimum"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    authors="${mod_authors}"
    description='''${mod_description}'''
    credits="Built against Glitchfiend's Serene Seasons; compatible alongside oros' Serene Seasons Fix - Revived."

[[dependencies.seasonplayerminimum]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.seasonplayerminimum]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.20.2)"
    ordering="NONE"
    side="BOTH"

[[dependencies.seasonplayerminimum]]
    modId="sereneseasons"
    mandatory=true
    versionRange="[9.0.0,)"
    ordering="AFTER"
    side="BOTH"
