general {
	# Message the console each time the season cycle pauses or resumes because of the seasonCyclePlayerMinimum gamerule. On by default.
	#Default: true
	print_messages_to_console = true
	# Whether to also broadcast those messages to all online players' chat, in addition to the console. Off by default.
	#Default: false
	display_message_on_server = true
	# Whether to still log those messages while doSeasonCycle is already set to false. Off by default
	#Default: false
	print_messages_if_doseasoncycle_false = false
	# Minimum seconds between chat messages to prevent spam. Only limits the chat, not the console log.
	#Range: 0 ~ 2147483647
	server_message_cooldown_seconds = 5
}

